### ISSUE TITLE
Cannot retrieve my big list of things to do from my project

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#98]
If I complete a project, and then need to do a similar project again, it'd be great to retrieve the original steps which I had put into the first task.

With the latest user interface, which removes all but the latest task of a project, I am unable to obtain my original list of things to do.  I can only access the very last task of the project, which only has the last few steps I did.

https://drive.google.com/file/d/1rg8sAzKFyKHKL3LT6P8BHClQIJvpa3NF/view?usp=drivesdk

I cannot even cut/paste from the history logs:

![capture](https://user-images.githubusercontent.com/38503093/53758406-b2a45080-3e8b-11e9-8404-6806e0a15d39.JPG)

**Comment by lgutro** [comment]
More thoughts on this:  As I worked on a 'project' yesterday, I made a big list in the first task.  Soon after, I realized I missed some steps.  I added those steps to the second task.  

When I repeat a similar project, it would be good to be able to retrieve all the steps from all the tasks, not just the first or the last one.   Perhaps a 'project log'?

**Comment by sharifyounes** [comment]
Is this addressed by the Dropdown on the Task Name step?

**Comment by lgutro** [comment]
The original issue is still a problem.  Let's say I write up a long list of things to do.  Then I miss one or more of the tick boxes.  The next time, the whole long list is no longer available either in 'Repeat' section, nor in the 'Continue' section.  And I cannot grab it from the Golden Hour history either.

The first comment 'More thoughts on this' is now fixed because I see now that I can repeat 1/3 2/3, 3/3 and the steps are preserved.
